const express = require('express');
const router = express.Router();
const { getDailyArticle, refreshDailyArticle, previewArticlesForRange } = require('../services/dailyArticle');
const pino = require('pino');

const logger = pino({ level: process.env.LOG_LEVEL || 'info' });

// Simple admin auth check (reuses existing ADMIN_USER/ADMIN_PASS)
function requireAdmin(req, res, next) {
  const auth = req.headers.authorization;
  if (!auth || !auth.startsWith('Basic ')) {
    return res.status(401).json({ error: 'Admin authentication required' });
  }
  const decoded = Buffer.from(auth.split(' ')[1], 'base64').toString();
  const [user, pass] = decoded.split(':');
  if (user !== process.env.ADMIN_USER || pass !== process.env.ADMIN_PASS) {
    return res.status(403).json({ error: 'Invalid credentials' });
  }
  next();
}

/**
 * GET /api/daily-article
 * Returns today's formatted article as JSON.
 * Optional ?date=YYYY-MM-DD query param.
 */
router.get('/', async (req, res) => {
  try {
    const date = req.query.date || undefined;
    const article = await getDailyArticle(date);
    if (!article) {
      return res.status(404).json({ error: 'No articles available' });
    }
    // Allow embedding from any Ralph domain
    res.set('Access-Control-Allow-Origin', '*');
    res.json({ article });
  } catch (err) {
    logger.error({ error: err.message }, 'Failed to get daily article');
    res.status(500).json({ error: 'Failed to retrieve daily article' });
  }
});

/**
 * POST /api/daily-article/refresh
 * Admin-only: clears cache for today (or ?date=) and regenerates.
 */
router.post('/refresh', requireAdmin, async (req, res) => {
  try {
    const date = req.query.date || req.body.date || undefined;
    const article = await refreshDailyArticle(date);
    if (!article) {
      return res.status(404).json({ error: 'No articles available' });
    }
    res.json({ article, refreshed: true });
  } catch (err) {
    logger.error({ error: err.message }, 'Failed to refresh daily article');
    res.status(500).json({ error: 'Failed to refresh daily article' });
  }
});

/**
 * GET /embed/daily-article
 * Self-contained HTML embed page. Works in an iframe.
 */
async function embedHandler(req, res) {
  try {
    const date = req.query.date || undefined;
    const article = await getDailyArticle(date);

    if (!article) {
      return res.status(404).send('<html><body><p>No article available today.</p></body></html>');
    }

    const html = renderEmbedHtml(article);
    res.set('Content-Type', 'text/html');
    res.set('Access-Control-Allow-Origin', '*');
    res.send(html);
  } catch (err) {
    logger.error({ error: err.message }, 'Failed to render daily article embed');
    res.status(500).send('<html><body><p>Error loading article.</p></body></html>');
  }
}

function escapeHtml(str) {
  if (!str) return '';
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function renderEmbedHtml(article) {
  const headline = escapeHtml(article.headline);
  const subtitle = escapeHtml(article.subtitle);
  const author = escapeHtml(article.author);
  const category = escapeHtml(article.category);
  const issue = escapeHtml(article.issue);
  const pullQuote = escapeHtml(article.pullQuote);
  const coverImage = article.coverImage || '/covers/Issue1cover.png';
  const pdfUrl = article.pdfUrl || '#';
  const pageRange = article.pageRange || '';
  // bodyHtml is trusted (generated by GPT-4o from our own content)
  const bodyHtml = article.bodyHtml || '';

  const issueLabel = issue ? `Ralph Magazine Issue ${issue}` : 'Ralph Magazine';
  const authorLine = author ? `By ${author}` : '';
  const byline = [authorLine, issueLabel].filter(Boolean).join(' | ');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${headline} - Ralph Magazine</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #FAFAFA;
      color: #1A1A1A;
      line-height: 1.7;
      -webkit-font-smoothing: antialiased;
    }

    .article-container {
      max-width: 720px;
      margin: 0 auto;
      background: #FFFFFF;
      min-height: 100vh;
    }

    /* Hero */
    .hero {
      position: relative;
      width: 100%;
      height: 360px;
      overflow: hidden;
    }
    .hero img {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
    .hero-overlay {
      position: absolute;
      bottom: 0; left: 0; right: 0;
      height: 60%;
      background: linear-gradient(transparent, rgba(0,0,0,0.7));
    }

    /* Category badge */
    .category-badge {
      display: inline-block;
      background: #EB008B;
      color: #FFFFFF;
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      padding: 4px 14px;
      border-radius: 20px;
      margin-bottom: 12px;
    }

    /* Content area */
    .content {
      padding: 32px 28px 48px;
    }

    .headline {
      font-size: 32px;
      font-weight: 800;
      line-height: 1.15;
      color: #0D0D0D;
      margin-bottom: 8px;
      letter-spacing: -0.02em;
    }

    .subtitle {
      font-size: 17px;
      color: #555;
      line-height: 1.5;
      margin-bottom: 16px;
      font-weight: 400;
    }

    .byline {
      font-size: 13px;
      color: #888;
      font-weight: 500;
      margin-bottom: 28px;
      padding-bottom: 20px;
      border-bottom: 1px solid #ECECEC;
    }

    /* Pull quote */
    .pull-quote {
      margin: 32px 0;
      padding: 20px 24px;
      border-left: 4px solid #EB008B;
      background: #FDF2F8;
      font-size: 18px;
      font-weight: 600;
      font-style: italic;
      color: #2D2D2D;
      line-height: 1.5;
      border-radius: 0 8px 8px 0;
    }

    /* Body text */
    .body-text p {
      margin-bottom: 18px;
      font-size: 16px;
      line-height: 1.75;
      color: #333;
    }
    .body-text h3 {
      font-size: 20px;
      font-weight: 700;
      color: #0D0D0D;
      margin: 32px 0 12px;
    }
    .body-text blockquote {
      margin: 24px 0;
      padding: 16px 20px;
      border-left: 3px solid #DDD;
      color: #555;
      font-style: italic;
    }

    /* Footer */
    .article-footer {
      padding: 24px 28px;
      border-top: 1px solid #ECECEC;
      display: flex;
      align-items: center;
      justify-content: space-between;
      flex-wrap: wrap;
      gap: 12px;
    }
    .read-more {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      color: #EB008B;
      font-size: 14px;
      font-weight: 600;
      text-decoration: none;
      transition: opacity 0.2s;
    }
    .read-more:hover { opacity: 0.8; }
    .read-more svg { width: 16px; height: 16px; }
    .branding {
      font-size: 12px;
      color: #AAA;
      font-weight: 500;
      letter-spacing: 0.05em;
      text-transform: uppercase;
    }

    /* Responsive */
    @media (max-width: 480px) {
      .hero { height: 240px; }
      .content { padding: 24px 20px 36px; }
      .headline { font-size: 26px; }
      .subtitle { font-size: 15px; }
      .pull-quote { font-size: 16px; padding: 16px 18px; }
      .body-text p { font-size: 15px; }
      .article-footer { padding: 20px; }
    }
  </style>
</head>
<body>
  <div class="article-container">
    <div class="hero">
      <img src="${escapeHtml(coverImage)}" alt="${issueLabel}" />
      <div class="hero-overlay"></div>
    </div>
    <div class="content">
      ${category ? `<span class="category-badge">${category}</span>` : ''}
      <h1 class="headline">${headline}</h1>
      ${subtitle ? `<p class="subtitle">${subtitle}</p>` : ''}
      <p class="byline">${byline}</p>
      ${pullQuote ? `<div class="pull-quote">&ldquo;${pullQuote}&rdquo;</div>` : ''}
      <div class="body-text">
        ${bodyHtml}
      </div>
    </div>
    <div class="article-footer">
      <a href="${escapeHtml(pdfUrl)}" target="_blank" rel="noopener" class="read-more">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>
        Read in magazine${pageRange ? ` (pp. ${escapeHtml(pageRange)})` : ''}
      </a>
      <span class="branding">Ralph Magazine</span>
    </div>
  </div>
</body>
</html>`;
}

/**
 * GET /api/daily-article/schedule?days=7
 * Returns metadata for today + N days ahead (no GPT-4o calls).
 */
router.get('/schedule', (req, res) => {
  try {
    const days = Math.min(Math.max(parseInt(req.query.days) || 7, 1), 30);
    const today = new Date().toISOString().split('T')[0];
    const schedule = previewArticlesForRange(today, days);
    res.json({ schedule });
  } catch (err) {
    logger.error({ error: err.message }, 'Failed to get article schedule');
    res.status(500).json({ error: 'Failed to retrieve schedule' });
  }
});

/**
 * GET /admin/daily-articles
 * Self-contained admin dashboard HTML page.
 */
function adminPageHandler(req, res) {
  res.set('Content-Type', 'text/html');
  res.send(renderAdminHtml());
}

function renderAdminHtml() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Articles Admin - Ralph Magazine</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #0D0D0D;
      color: #F0F0F0;
      min-height: 100vh;
      -webkit-font-smoothing: antialiased;
    }

    /* Login */
    .login-overlay {
      position: fixed; inset: 0;
      display: flex; align-items: center; justify-content: center;
      background: #0D0D0D;
      z-index: 1000;
    }
    .login-overlay.hidden { display: none; }
    .login-card {
      background: rgba(255,255,255,0.06);
      backdrop-filter: blur(20px);
      border: 1px solid rgba(255,255,255,0.1);
      border-radius: 16px;
      padding: 40px;
      width: 360px;
      text-align: center;
    }
    .login-card h2 {
      font-size: 22px;
      font-weight: 700;
      margin-bottom: 6px;
      color: #EB008B;
    }
    .login-card p {
      font-size: 13px;
      color: #888;
      margin-bottom: 24px;
    }
    .login-card input {
      display: block;
      width: 100%;
      padding: 10px 14px;
      margin-bottom: 12px;
      border: 1px solid rgba(255,255,255,0.15);
      border-radius: 8px;
      background: rgba(255,255,255,0.05);
      color: #F0F0F0;
      font-size: 14px;
      font-family: inherit;
      outline: none;
      transition: border-color 0.2s;
    }
    .login-card input:focus { border-color: #EB008B; }
    .login-card input::placeholder { color: #666; }
    .login-error {
      color: #FF4444;
      font-size: 12px;
      margin-bottom: 12px;
      display: none;
    }
    .btn {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 6px;
      padding: 10px 20px;
      border: none;
      border-radius: 8px;
      font-size: 14px;
      font-weight: 600;
      font-family: inherit;
      cursor: pointer;
      transition: all 0.2s;
    }
    .btn-primary {
      background: #EB008B;
      color: #FFF;
      width: 100%;
    }
    .btn-primary:hover { background: #D4007D; }
    .btn-secondary {
      background: rgba(255,255,255,0.08);
      color: #F0F0F0;
      border: 1px solid rgba(255,255,255,0.15);
    }
    .btn-secondary:hover { background: rgba(255,255,255,0.14); }
    .btn:disabled { opacity: 0.5; cursor: not-allowed; }

    /* Dashboard */
    .dashboard { display: none; max-width: 960px; margin: 0 auto; padding: 32px 24px 64px; }
    .dashboard.visible { display: block; }

    /* Header */
    .header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 32px;
      flex-wrap: wrap;
      gap: 12px;
    }
    .header h1 {
      font-size: 24px;
      font-weight: 800;
      letter-spacing: -0.02em;
    }
    .header h1 span { color: #EB008B; }
    .header-actions { display: flex; gap: 8px; align-items: center; }
    .user-label { font-size: 12px; color: #888; margin-right: 4px; }

    /* Today card */
    .today-card {
      background: rgba(255,255,255,0.04);
      backdrop-filter: blur(20px);
      border: 1px solid rgba(255,255,255,0.08);
      border-radius: 16px;
      overflow: hidden;
      margin-bottom: 32px;
    }
    .today-card .card-inner {
      display: flex;
      gap: 0;
    }
    .today-card .cover-side {
      width: 220px;
      min-height: 280px;
      flex-shrink: 0;
      overflow: hidden;
      position: relative;
    }
    .today-card .cover-side img {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
    .today-card .info-side {
      flex: 1;
      padding: 28px 32px;
      display: flex;
      flex-direction: column;
      justify-content: center;
    }
    .section-label {
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      color: #EB008B;
      margin-bottom: 12px;
    }
    .today-card .category-badge {
      display: inline-block;
      background: #EB008B;
      color: #FFF;
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      padding: 3px 12px;
      border-radius: 20px;
      margin-bottom: 10px;
    }
    .today-card .headline {
      font-size: 24px;
      font-weight: 800;
      line-height: 1.2;
      color: #FFF;
      margin-bottom: 8px;
      letter-spacing: -0.01em;
    }
    .today-card .meta {
      font-size: 13px;
      color: #999;
      margin-bottom: 20px;
      line-height: 1.5;
    }
    .today-card .actions {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
    }

    /* Schedule table */
    .schedule-section { margin-top: 8px; }
    .schedule-section .section-label { margin-bottom: 16px; }
    .schedule-table {
      width: 100%;
      border-collapse: collapse;
      background: rgba(255,255,255,0.03);
      border-radius: 12px;
      overflow: hidden;
      border: 1px solid rgba(255,255,255,0.06);
    }
    .schedule-table th {
      text-align: left;
      padding: 12px 16px;
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: #888;
      background: rgba(255,255,255,0.04);
      border-bottom: 1px solid rgba(255,255,255,0.06);
    }
    .schedule-table td {
      padding: 12px 16px;
      font-size: 13px;
      color: #CCC;
      border-bottom: 1px solid rgba(255,255,255,0.04);
      vertical-align: middle;
    }
    .schedule-table tr:last-child td { border-bottom: none; }
    .schedule-table tr:hover td { background: rgba(255,255,255,0.03); }
    .schedule-table .date-cell {
      font-weight: 600;
      color: #FFF;
      white-space: nowrap;
    }
    .schedule-table .day-cell { color: #999; }
    .schedule-table .title-cell {
      font-weight: 500;
      color: #EEE;
      max-width: 260px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    .status-badge {
      display: inline-block;
      font-size: 11px;
      font-weight: 600;
      padding: 2px 10px;
      border-radius: 10px;
    }
    .status-cached { background: rgba(52,199,89,0.15); color: #34C759; }
    .status-pending { background: rgba(255,255,255,0.08); color: #888; }
    .preview-link {
      color: #EB008B;
      text-decoration: none;
      font-weight: 600;
      font-size: 12px;
    }
    .preview-link:hover { text-decoration: underline; }
    .today-row td { background: rgba(235,0,139,0.05); }

    /* Loading */
    .loading {
      text-align: center;
      padding: 40px;
      color: #888;
      font-size: 14px;
    }
    .spinner {
      display: inline-block;
      width: 20px; height: 20px;
      border: 2px solid rgba(255,255,255,0.1);
      border-top-color: #EB008B;
      border-radius: 50%;
      animation: spin 0.8s linear infinite;
      margin-right: 8px;
      vertical-align: middle;
    }
    @keyframes spin { to { transform: rotate(360deg); } }

    /* Responsive */
    @media (max-width: 640px) {
      .today-card .card-inner { flex-direction: column; }
      .today-card .cover-side { width: 100%; min-height: 200px; max-height: 220px; }
      .today-card .info-side { padding: 20px; }
      .today-card .headline { font-size: 20px; }
      .schedule-table { font-size: 12px; }
      .schedule-table th, .schedule-table td { padding: 10px 12px; }
      .header h1 { font-size: 20px; }
      .hide-mobile { display: none; }
    }
  </style>
</head>
<body>

  <!-- Login overlay -->
  <div class="login-overlay" id="loginOverlay">
    <div class="login-card">
      <h2>Ralph Admin</h2>
      <p>Daily Articles Dashboard</p>
      <input type="text" id="loginUser" placeholder="Username" autocomplete="username" />
      <input type="password" id="loginPass" placeholder="Password" autocomplete="current-password" />
      <div class="login-error" id="loginError">Invalid credentials</div>
      <button class="btn btn-primary" id="loginBtn" onclick="doLogin()">Login</button>
    </div>
  </div>

  <!-- Dashboard -->
  <div class="dashboard" id="dashboard">
    <div class="header">
      <h1><span>Ralph</span> Daily Articles</h1>
      <div class="header-actions">
        <span class="user-label" id="userLabel"></span>
        <button class="btn btn-secondary" id="syncBtn" onclick="syncPdfs()">Sync PDFs</button>
        <button class="btn btn-secondary" onclick="doLogout()">Logout</button>
      </div>
    </div>

    <!-- Today's article -->
    <div id="todaySection">
      <div class="section-label">Today's Article</div>
      <div class="today-card" id="todayCard">
        <div class="loading" id="todayLoading"><span class="spinner"></span>Loading today's article...</div>
      </div>
    </div>

    <!-- 7-day schedule -->
    <div class="schedule-section">
      <div class="section-label">7-Day Schedule</div>
      <div id="scheduleContainer">
        <div class="loading" id="scheduleLoading"><span class="spinner"></span>Loading schedule...</div>
      </div>
    </div>
  </div>

<script>
(function() {
  const CREDS_KEY = 'ralph_admin_creds';

  // --- Auth ---
  function getAuth() {
    const stored = localStorage.getItem(CREDS_KEY);
    if (!stored) return null;
    try {
      const decoded = atob(stored);
      const [u, p] = decoded.split(':');
      return { user: u, pass: p, header: 'Basic ' + stored };
    } catch { return null; }
  }

  function saveAuth(user, pass) {
    localStorage.setItem(CREDS_KEY, btoa(user + ':' + pass));
  }

  function clearAuth() {
    localStorage.removeItem(CREDS_KEY);
  }

  // --- Login ---
  window.doLogin = async function() {
    const user = document.getElementById('loginUser').value.trim();
    const pass = document.getElementById('loginPass').value;
    const errEl = document.getElementById('loginError');
    errEl.style.display = 'none';

    if (!user || !pass) { errEl.textContent = 'Please enter credentials'; errEl.style.display = 'block'; return; }

    // Validate by hitting an admin endpoint
    try {
      const res = await fetch('/api/daily-article/refresh', {
        method: 'POST',
        headers: { 'Authorization': 'Basic ' + btoa(user + ':' + pass), 'Content-Type': 'application/json' }
      });
      if (res.status === 401 || res.status === 403) {
        errEl.textContent = 'Invalid credentials';
        errEl.style.display = 'block';
        return;
      }
      // Success — save & show dashboard
      saveAuth(user, pass);
      showDashboard(user);
    } catch (e) {
      errEl.textContent = 'Connection error';
      errEl.style.display = 'block';
    }
  };

  // Enter key on password field
  document.getElementById('loginPass').addEventListener('keydown', function(e) {
    if (e.key === 'Enter') window.doLogin();
  });

  window.doLogout = function() {
    clearAuth();
    document.getElementById('dashboard').classList.remove('visible');
    document.getElementById('loginOverlay').classList.remove('hidden');
  };

  function showDashboard(user) {
    document.getElementById('loginOverlay').classList.add('hidden');
    document.getElementById('dashboard').classList.add('visible');
    document.getElementById('userLabel').textContent = user;
    loadTodayArticle();
    loadSchedule();
  }

  // --- Data loading ---
  async function loadTodayArticle() {
    const card = document.getElementById('todayCard');
    const loading = document.getElementById('todayLoading');
    loading.style.display = 'block';

    try {
      const res = await fetch('/api/daily-article');
      if (!res.ok) throw new Error('No article');
      const data = await res.json();
      const a = data.article;
      const issueLbl = a.issue ? 'Issue ' + a.issue : '';
      const metaParts = [a.author, issueLbl, a.pageRange ? 'pp. ' + a.pageRange : ''].filter(Boolean);

      card.innerHTML = '<div class="card-inner">' +
        '<div class="cover-side"><img src="' + escHtml(a.coverImage || '/covers/Issue1cover.png') + '" alt="Cover" /></div>' +
        '<div class="info-side">' +
          '<div class="section-label">Today\\'s Article</div>' +
          (a.category ? '<span class="category-badge">' + escHtml(a.category) + '</span>' : '') +
          '<div class="headline">' + escHtml(a.headline) + '</div>' +
          '<div class="meta">' + escHtml(metaParts.join(' \\u00B7 ')) + '</div>' +
          '<div class="actions">' +
            '<a href="/embed/daily-article" target="_blank" class="btn btn-primary" style="width:auto;">View Article</a>' +
            '<button class="btn btn-secondary" onclick="refreshArticle()" id="refreshBtn">Refresh</button>' +
          '</div>' +
        '</div>' +
      '</div>';
    } catch (e) {
      card.innerHTML = '<div class="loading">No article available. Have you synced PDFs?</div>';
    }
  }

  window.refreshArticle = async function() {
    const btn = document.getElementById('refreshBtn');
    if (btn) { btn.disabled = true; btn.textContent = 'Refreshing...'; }

    const auth = getAuth();
    if (!auth) { window.doLogout(); return; }

    try {
      await fetch('/api/daily-article/refresh', {
        method: 'POST',
        headers: { 'Authorization': auth.header, 'Content-Type': 'application/json' }
      });
      await loadTodayArticle();
    } catch (e) {
      if (btn) { btn.disabled = false; btn.textContent = 'Refresh'; }
    }
  };

  window.syncPdfs = async function() {
    const btn = document.getElementById('syncBtn');
    const auth = getAuth();
    if (!auth) { window.doLogout(); return; }

    btn.disabled = true;
    btn.textContent = 'Syncing...';

    try {
      const res = await fetch('/api/sync-pdfs/run', {
        method: 'POST',
        headers: { 'Authorization': auth.header, 'Content-Type': 'application/json' }
      });
      const data = await res.json();
      if (data.ok) {
        const msg = data.files_processed > 0
          ? 'Synced ' + data.files_processed + ' PDF(s). Reloading...'
          : 'All PDFs already synced (' + data.files_skipped + ' skipped).';
        btn.textContent = msg;
        if (data.files_processed > 0) {
          setTimeout(() => { loadTodayArticle(); loadSchedule(); btn.textContent = 'Sync PDFs'; btn.disabled = false; }, 1500);
        } else {
          setTimeout(() => { btn.textContent = 'Sync PDFs'; btn.disabled = false; }, 2000);
        }
      } else {
        btn.textContent = 'Sync failed';
        setTimeout(() => { btn.textContent = 'Sync PDFs'; btn.disabled = false; }, 2000);
      }
    } catch (e) {
      btn.textContent = 'Sync error';
      setTimeout(() => { btn.textContent = 'Sync PDFs'; btn.disabled = false; }, 2000);
    }
  };

  async function loadSchedule() {
    const container = document.getElementById('scheduleContainer');
    try {
      const res = await fetch('/api/daily-article/schedule?days=7');
      if (!res.ok) throw new Error('Failed');
      const data = await res.json();
      const rows = data.schedule;
      const today = new Date().toISOString().split('T')[0];

      if (!rows || rows.length === 0) {
        container.innerHTML = '<div class="loading">No articles available.</div>';
        return;
      }

      let html = '<table class="schedule-table"><thead><tr>' +
        '<th>Date</th><th>Day</th><th>Category</th><th>Title</th>' +
        '<th class="hide-mobile">Author</th><th class="hide-mobile">Issue</th>' +
        '<th>Status</th><th></th>' +
        '</tr></thead><tbody>';

      for (const row of rows) {
        const isToday = row.date === today;
        const dateDisp = row.date.substring(5); // MM-DD
        html += '<tr class="' + (isToday ? 'today-row' : '') + '">' +
          '<td class="date-cell">' + escHtml(dateDisp) + (isToday ? ' <span style="color:#EB008B;font-size:10px;">TODAY</span>' : '') + '</td>' +
          '<td class="day-cell">' + escHtml(row.dayName) + '</td>' +
          '<td>' + escHtml(row.category || '—') + '</td>' +
          '<td class="title-cell">' + escHtml(row.title || '—') + '</td>' +
          '<td class="hide-mobile">' + escHtml(row.author || '—') + '</td>' +
          '<td class="hide-mobile">' + (row.issue ? escHtml(row.issue) : '—') + '</td>' +
          '<td>' + (row.isCached
            ? '<span class="status-badge status-cached">Cached</span>'
            : '<span class="status-badge status-pending">Pending</span>') + '</td>' +
          '<td><a href="/embed/daily-article?date=' + encodeURIComponent(row.date) + '" target="_blank" class="preview-link">Preview</a></td>' +
          '</tr>';
      }

      html += '</tbody></table>';
      container.innerHTML = html;
    } catch (e) {
      container.innerHTML = '<div class="loading">Failed to load schedule.</div>';
    }
  }

  function escHtml(s) {
    if (!s) return '';
    const d = document.createElement('div');
    d.textContent = s;
    return d.innerHTML;
  }

  // --- Init ---
  const auth = getAuth();
  if (auth) {
    showDashboard(auth.user);
  }
})();
</script>
</body>
</html>`;
}

module.exports = { router, embedHandler, adminPageHandler };
